[package]
name = "sgcount"
version = "0.1.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxread = "0.2"
hashbrown = "0.12"
anyhow = "1"
clap = { version = "3.2", features = ["derive"] }
indicatif = {version = "*", features = ["rayon"]}
rayon = "1.5"
ndarray = "0.15"
ndarray-stats = "0.5"
