[package]
name = "sgcount"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxread = "0.1"
anyhow = "1"
clap = { version = "3.2", features = ["derive"] }
ndarray = "0.15"
ndarray-stats = "0.5"
