[package]
name = "sgcount"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxread = "0.1"
anyhow = "1"
clap = "3.2"
