use std::collections::HashMap;
use super::{Trimmer, Library, Permuter};

/// Struct to handle the mapping between the trimmed records generated by [`Trimmer`]
/// and the sequences found in the [`Library`]. It also has an optional argument for
/// unambiguous sequence permutations contained within [`Permuter`]. 
pub struct Counter {
    results: HashMap<String, usize>
}
impl Counter {
    
    /// Initializes counting of reads from the [`Trimmer`] against reads within
    /// the [`Library`]. Optional argument for the unambiguous sequence permutations
    /// contained within [`Permuter`].
    pub fn new(
        trimmer: Trimmer,
        library: &Library,
        permuter: &Option<Permuter>) -> Self {

        let results = Self::count(trimmer, library, permuter);
        Self { results }
    }

    /// Publically exposes the results dictionary and returns either the observed count
    /// of a specific match or a zero if there were no matches.
    pub fn get_value(&self, token: &str) -> &usize {
        match self.results.get(token) {
            Some(c) => c,
            None => &0
        }
    }

    /// Assignment process against the [`Library`].
    fn check_library<'a>(token: &str, library: &'a Library) -> Option<&'a String> {
        library.contains(token)
    }


    /// Assignment process against the [`Permuter`]. This will only execute if the [`Permuter`] is
    /// optionally not [`None`].
    fn check_permuter<'a>(token: &str, permuter: &'a Option<Permuter>) -> Option<&'a String> {
        match permuter {
            Some(p) => p.contains(token),
            None => None
        }

    }

    /// Assignment process of the struct performing the string matching.
    /// Tokens are first matched against the library (exact matches)
    /// and if none are found then are matched against the permutations (oneoff matches).
    /// If still none are found then it returns [`None`].
    fn assign<'a>(token: &str, library: &'a Library, permuter: &Option<Permuter>) -> Option<&'a String> {
        match Self::check_library(token, library) {
            Some(s) => Some(s),
            None => match Self::check_permuter(token, permuter) {
                Some(s) => library.alias(s),
                None => None
            }
        }

    }

    /// Main functionality of the struct. Performs the counting operation.
    /// Input sequences are assigned to their respective match within the 
    /// library or the permutations. 
    /// Finally they are folded into a [`HashMap`] whose keys are the sequence
    /// alias within the library and the values the number of observed counts.
    fn count<'a>(
            trimmer: Trimmer, 
            library: &Library, 
            permuter: &Option<Permuter>) -> HashMap<String, usize> 
    {
        trimmer
            .into_iter()
            .map(|x| x.seq().to_string())
            .filter_map(|x| Self::assign(&x, library, permuter))
            .fold(HashMap::new(), |mut accum, x| {
                *accum.entry(x.to_string()).or_insert(0) += 1;
                accum
            })
    }
}

#[cfg(test)]
mod test {

    use fxread::{FastaReader, FastxRead, Record};
    use super::{Library, Trimmer, Counter, Permuter};

    fn trim_reader(distance: bool) -> Box<dyn FastxRead<Item = Record>> {
        let sequence: &'static [u8] = match distance {
            false => b">seq.0\nACTG\n",
            true => b">seq.0\nAGTG\n",
        };
        Box::new(FastaReader::new(sequence))
    }

    fn lib_reader() -> Box<dyn FastxRead<Item = Record>> {
        let sequence: &'static [u8] = b">seq.0\nACTG\n";
        Box::new(FastaReader::new(sequence))
    }

    fn trimmer(distance: bool) -> Trimmer {
        Trimmer::from_reader(trim_reader(distance), 0, 4)
    }

    fn library() -> Library {
        Library::from_reader(lib_reader()).unwrap()
    }

    fn permuter() -> Permuter {
        Permuter::new(library().keys())
    }

    #[test]
    fn count_no_distance_no_permute() {
        let trimmer = trimmer(false);
        let library = library();
        let count = Counter::new(trimmer, &library, &None);
        assert_eq!(*count.get_value("seq.0"), 1);
    }

    #[test]
    fn count_no_distance_with_permute() {
        let trimmer = trimmer(true);
        let library = library();
        let count = Counter::new(trimmer, &library, &None);
        assert_eq!(*count.get_value("seq.0"), 0);
    }

    #[test]
    fn count_with_distance_no_permute() {
        let trimmer = trimmer(true);
        let library = library();
        let count = Counter::new(trimmer, &library, &None);
        assert_eq!(*count.get_value("seq.0"), 0);
    }

    #[test]
    fn count_with_distance_with_permute() {
        let trimmer = trimmer(true);
        let library = library();
        let permuter = permuter();
        let count = Counter::new(trimmer, &library, &Some(permuter));
        assert_eq!(*count.get_value("seq.0"), 1);
    }
}
