use fxread::{FastxRead, Record};
use hashbrown::HashMap;
use crate::Offset;

use super::{Library, Permuter};

/// Struct to handle the mapping between the trimmed records generated by [`FastxRead`]
/// and the sequences found in the [`Library`]. It also has an optional argument for
/// unambiguous sequence permutations contained within [`Permuter`]. 
pub struct Counter {
    results: HashMap<String, usize>
}
impl Counter {
    
    /// Initializes counting of reads from the [`FastxRead`] object within
    /// the [`Library`]. Optional argument for the unambiguous sequence permutations
    /// contained within [`Permuter`].
    pub fn new(
        reader: Box<dyn FastxRead<Item = Record>>,
        library: &Library,
        permuter: &Option<Permuter>,
        offset: Offset,
        size: usize) -> Self {

        let results = Self::count(reader, library, permuter, offset, size);
        Self { results }
    }

    /// Publically exposes the results dictionary and returns either the observed count
    /// of a specific match or a zero if there were no matches.
    pub fn get_value(&self, token: &str) -> &usize {
        match self.results.get(token) {
            Some(c) => c,
            None => &0
        }
    }

    /// Assignment process against the [`Library`].
    fn check_library<'a>(token: &str, library: &'a Library) -> Option<&'a String> {
        library.contains(token)
    }


    /// Assignment process against the [`Permuter`]. This will only execute if the [`Permuter`] is
    /// optionally not [`None`].
    fn check_permuter<'a>(token: &str, permuter: &'a Option<Permuter>) -> Option<&'a String> {
        match permuter {
            Some(p) => p.contains(token),
            None => None
        }
    }

    /// Assignment process of the struct performing the string matching.
    /// Tokens are first matched against the library (exact matches)
    /// and if none are found then are matched against the permutations (oneoff matches).
    /// If still none are found then it returns [`None`].
    fn assign<'a>(
            record: &Record, 
            library: &'a Library, 
            permuter: &Option<Permuter>,
            offset: Offset,
            size: usize) -> Option<&'a String> 
    {
        //let token = Self::trim_sequence(&record, offset, size);
        let token = match offset {
            Offset::Forward(index) => Self::trim_forward_sequence(record, index, size).to_owned(),
            Offset::Reverse(index) => Self::trim_reverse_sequence(record, index, size),
        };
        match Self::check_library(&token, library) {
            Some(s) => Some(s),
            None => match Self::check_permuter(&token, permuter) {
                Some(s) => library.alias(s),
                None => None
            }
        }
    }

    fn trim_forward_sequence(
            record: &Record,
            offset: usize,
            size: usize) -> &str 
    {
        let seq = std::str::from_utf8(&record
            .seq()
            .as_bytes()[offset..offset+size]);
        match seq {
            Ok(s) => s,
            Err(why) => panic!("{}", why)
        }
    }

    fn trim_reverse_sequence(
            record: &Record,
            offset: usize,
            size: usize) -> String 
    {
        let seq = String::from_utf8(record
            .seq_rev_comp().expect(&format!("Unexpected nucleotides found in {:?}", record))
            .as_bytes()[offset..offset+size]
            .to_vec());
        match seq {
            Ok(s) => s,
            Err(why) => panic!("{}", why)
        }
    }

    /// Main functionality of the struct. Performs the counting operation.
    /// Input sequences are assigned to their respective match within the 
    /// library or the permutations. 
    /// Finally they are folded into a [`HashMap`] whose keys are the sequence
    /// alias within the library and the values the number of observed counts.
    fn count<'a>(
            reader: Box<dyn FastxRead<Item = Record>>, 
            library: &Library, 
            permuter: &Option<Permuter>,
            offset: Offset,
            size: usize) -> HashMap<String, usize> 
    {
       reader 
            .into_iter()
            .filter_map(|x| Self::assign(&x, library, permuter, offset, size))
            .fold(HashMap::new(), |mut accum, x| {
                *accum.entry(x.to_string()).or_insert(0) += 1;
                accum
            })
    }
}

#[cfg(test)]
mod test {

    use fxread::{FastaReader, FastxRead, Record};
    use super::{Library, Counter, Permuter};
    use crate::Offset;

    fn trim_reader(distance: bool) -> Box<dyn FastxRead<Item = Record>> {
        let sequence: &'static [u8] = match distance {
            false => b">seq.0\nACTG\n",
            true => b">seq.0\nAGTG\n",
        };
        Box::new(FastaReader::new(sequence))
    }

    fn lib_reader() -> Box<dyn FastxRead<Item = Record>> {
        let sequence: &'static [u8] = b">seq.0\nACTG\n";
        Box::new(FastaReader::new(sequence))
    }

    fn library() -> Library {
        Library::from_reader(lib_reader()).unwrap()
    }

    fn permuter() -> Permuter {
        Permuter::new(library().keys())
    }

    #[test]
    fn count_no_distance_no_permute() {
        let trimmer = trim_reader(false);
        let library = library();
        let count = Counter::new(trimmer, &library, &None, Offset::Forward(0), 4);
        assert_eq!(*count.get_value("seq.0"), 1);
    }

    #[test]
    fn count_no_distance_with_permute() {
        let trimmer = trim_reader(true);
        let library = library();
        let count = Counter::new(trimmer, &library, &None, Offset::Forward(0), 4);
        assert_eq!(*count.get_value("seq.0"), 0);
    }

    #[test]
    fn count_with_distance_no_permute() {
        let trimmer = trim_reader(true);
        let library = library();
        let count = Counter::new(trimmer, &library, &None, Offset::Forward(0), 4);
        assert_eq!(*count.get_value("seq.0"), 0);
    }

    #[test]
    fn count_with_distance_with_permute() {
        let trimmer = trim_reader(true);
        let library = library();
        let permuter = permuter();
        let count = Counter::new(trimmer, &library, &Some(permuter), Offset::Forward(0), 4);
        assert_eq!(*count.get_value("seq.0"), 1);
    }
}
